[parity]
chain="./poa.json"
base_path="./data/"

[rpc]
port=8545
interface="local"
apis=["all"]
server_threads = 10

[websockets]
port = 8546
interface = "local"
apis = ["all"]

[network]
port = 30303

[account]
password = ["./password"]

[mining]
engine_signer = "0x3f45B69eE919b06853B6358Aeaa5e043c83Bd366"
gas_floor_target = "240000000"
gas_cap = "300000000"
min_gas_price = 0
force_sealing = true
reseal_on_txs = "all"
